services:
  demo-gpio-daemon:
    build:
      context: .
      dockerfile: container/Containerfile
    container_name: demo-gpio-daemon
    image: demo-gpio-daemon:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace
